
name: CI, News Dashboard & Model Training

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

env:
  NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
  MLFLOW_TRACKING_URI: http://127.0.0.1:5000

jobs:
  ci-full-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pipeline repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run fetch_news to get latest headlines
      run: |
        python fetch_news.py || echo "⚠️ News fetch failed or empty"
        if [ -f news_dashboard.html ]; then
          echo "✅ Dashboard generated:"
          ls -lh news_dashboard.html
        else
          echo "🚫 No dashboard created"
        fi

    - name: Train ML model on latest data
      run: |
        if [ -d data ]; then
          echo "📊 Training model on latest data..."
          python train_model.py
        else
          echo "⚠️ No data found. Skipping model training."
        fi

    - name: Checkout GitHub Pages repo
      uses: actions/checkout@v3
      with:
        repository: bahman7891/bahmanroostaei.github.io
        path: pages
        token: ${{ secrets.GH_TOKEN }}

    - name: Copy dashboard to GitHub Pages repo
      run: |
        if [ -f news_dashboard.html ]; then
          cp news_dashboard.html pages/news_dashboard.html
          echo "✅ Copied dashboard to Pages repo"
        else
          echo "⚠️ No dashboard file to copy"
        fi

    - name: Commit and push dashboard
      run: |
        cd pages
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add news_dashboard.html || true
        git commit -m "Update news dashboard and model [automated]" || echo "No changes to commit"
        git push origin main || echo "Nothing to push"
