name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_ACR_USERNAME }}
        password: ${{ secrets.AZURE_ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/news-pipeline:latest .

    - name: Push Docker image to ACR
      run: |
        docker push ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/news-pipeline:latest
